# Generated by Django 2.0.2 on 2018-05-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('introduction', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(verbose_name='date last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('introduction', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('last_modified', models.DateTimeField(verbose_name='date last modified')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptures.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('last_modified', models.DateTimeField(verbose_name='date last modified')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptures.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('title_page', models.TextField()),
                ('introduction', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(verbose_name='date last modified')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptures.Volume'),
        ),
    ]
