# Generated by Django 2.0.2 on 2018-05-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
